runtime: php55
api_version: 1
threadsafe: true

handlers:

# Application static resources

- url: /css
  static_dir: public/css

- url: /js
  static_dir: public/js

- url: /img
  static_dir: public/img

- url: /fonts
  static_dir: public/fonts
  
  
- url: /login.php
  script: public/login.php
  
  
- url: /logout.php
  script: public/logout.php

  
  
- url: /navbar.php
  script: public/navbar.php

  
- url: /index.php
  script: public/index.php
  
- url: /itemDetail.php
  script: public/itemDetail.php
  
- url: /addToCart.php
  script: public/addToCart.php
  
  
- url: /cartItems.php
  script: public/cartItems.php
  
- url: /updateCart.php
  script: public/updateCart.php
  

- url: /c/wc.php
  script: public/c/wc.php
  login: admin

# Default handler

- url: .*
  script: public/index.php
